### ISSUE TITLE
how to get latest record in anvis.

### ISSUE THREAD

**Issue by AhmedRazaTester** [WhiteaglePT/node-anviz#2]
i mark atteandance today. how can i get this.
Please Help.

`const anviz = require("node-anviz");
let request = new anviz.Request("192.168.10.167");

// request
//   .execute("getRecordInformation", 1)
//   .on("error", function (err) {
//     console.info("ERROR", err);
//   })
//   .on("complete", function (res, raw) {
//     console.info(res);
//   });

request
  .execute("downloadAttendanceRecords", 1, [1, 25])
  .on("error", function (err) {
    console.info("ERROR", err);
  })
  .on("complete", function (res, raw) {
    console.info("===>>>", res, raw);
    request.close();
  });
`
And i get this reponse

`===>>> [
  { user: 3, time: 2017-10-15T06:11:06.000Z, action: 0 },
  { user: 3, time: 2017-10-16T06:11:10.000Z, action: 0 },
  { user: 1, time: 2017-11-25T13:36:43.000Z, action: 0 },
  { user: 1, time: 2017-11-25T13:36:44.000Z, action: 0 },
  { user: 1, time: 2017-11-25T13:36:51.000Z, action: 0 },
  { user: 1, time: 2017-11-25T13:36:54.000Z, action: 0 },
  { user: 2, time: 2017-11-25T13:36:59.000Z, action: 0 },
  { user: 3, time: 2017-11-25T13:37:10.000Z, action: 0 },
  { user: 1044486, time: 2017-11-25T13:37:13.000Z, action: 0 },
  { user: 1044486, time: 2017-11-25T13:37:14.000Z, action: 0 },
  { user: 1044486, time: 2017-11-25T13:37:16.000Z, action: 0 },
  { user: 1, time: 2017-11-25T13:37:55.000Z, action: 0 },
  { user: 1, time: 2017-11-25T14:33:07.000Z, action: 0 },
  { user: 1, time: 2017-11-29T09:53:12.000Z, action: 0 },
  { user: 1, time: 2017-12-26T07:28:12.000Z, action: 0 },
  { user: 8, time: 2017-12-26T07:29:43.000Z, action: 0 },
  { user: 1, time: 2017-12-28T12:33:09.000Z, action: 0 },
  { user: 1, time: 2017-12-28T12:33:11.000Z, action: 0 },
  { user: 1, time: 2018-01-01T07:10:22.000Z, action: 0 },
  { user: 1, time: 2018-01-01T07:10:27.000Z, action: 1 },
  { user: 1, time: 2018-01-01T07:10:34.000Z, action: 0 },
  { user: 1, time: 2018-01-01T07:14:46.000Z, action: 0 },
  { user: 1, time: 2018-01-01T07:14:48.000Z, action: 0 },
  { user: 1, time: 2018-01-01T07:14:55.000Z, action: 0 },
  { user: 1, time: 2018-01-01T10:32:01.000Z, action: 0 }
] {
  device: 1,
  cmd: 'downloadAttendanceRecords',
  ack: 0,
  len: 96,
  body: <Buffer 19 00 00 00 00 03 21 74 ad 4a 01 00 00 00 00 00 00 00 00 03 21 75 fe ce 01 00 00 00 00 00 00 00 00 01 21 ab 23 3b 01 00 00 00 00 00 00 00 00 01 21 ab ... 301 more bytes>,
  crc: <Buffer b8 cf>
}`

**Comment by WhiteaglePT** [comment]
Hello,

I advice you to read the TCB Communications Protocol PDF (you can find it on the dev/ directory).

You cannot query records by date directly to the device, that's not how the anviz protocol is designed.

_downloadAttendanceRecords_ returns all the records since the last time _eraseNewRecordsFlag_ was called.

So you want to always use _downloadAttendanceRecords_ to download all records and then call _eraseNewRecordsFlag_.
This will make that the next time you call downloadAttendanceRecords you'll only get new records - and not old ones as you're getting.

Just don't forget to call _eraseNewRecordsFlag_ after downloading to make sure that the next time you download records you only get new ones.

I will be closing this issue as it's not an issue, but any questions feel free to reopen it.
